version: '3.8'

services:
  db:
    build: ./db
    container_name: postgresB2W
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  pgadmin:
    depends_on:
        db:
          condition: service_healthy
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

  server:
    depends_on:
      db:
        condition: service_healthy
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - data_volume:/app/b2wData

volumes:
  data_volume: