version: '3.8'

services:
  db:
    image: postgres
    container_name: postgresB2W
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - data_volume:/app/b2wData

volumes:
  data_volume: